# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6EvqFfN8BeSzNsLfQbCSW12mYTnrV5J
"""

import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])


np.random.seed(1)
W1 = np.random.randn(2, 2)   # input -> hidden
W2 = np.random.randn(2, 1)   # hidden -> output

lr = 0.5
epochs = 5000


for _ in range(epochs):

    hidden = sigmoid(np.dot(X, W1))
    output = sigmoid(np.dot(hidden, W2))

    error = y - output


    d_output = error * sigmoid_derivative(output)
    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(hidden)


    W2 += hidden.T.dot(d_output) * lr
    W1 += X.T.dot(d_hidden) * lr


print("Output after training:")
print(np.round(output))