# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6EvqFfN8BeSzNsLfQbCSW12mYTnrV5J
"""

import numpy as np

# Step function (activation)
def step(x):
    return 1 if x >= 0 else 0

# Training data (AND gate)
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0, 0, 0, 1])

# Initialize weights and bias
W = np.zeros(2)
b = 0

learning_rate = 0.1
epochs = 10

# Training
for _ in range(epochs):
    for i in range(len(X)):
        linear = np.dot(X[i], W) + b   # weighted sum
        y_pred = step(linear)          # prediction
        error = y[i] - y_pred          # error

        # update rule
        W += learning_rate * error * X[i]
        b += learning_rate * error

# Testing
print("Final Weights:", W)
print("Final Bias:", b)

for x in X:
    linear = np.dot(x, W) + b
    print(x, "->", step(linear))